[[server]]
name = "a2cname-server"
tags = ["dns-a2cname", "instance"]
[server.config]
address = "https://a2cname.shark-perch.ts.net:8120"
region = "pve1:vm/5353"
enabled = true

##

[[stack]]
name = "dns-a2cname_1"
tags = ["dns-a2cname", "instance"]
[stack.config]
server = "a2cname-server"
git_account = "b-"
repo = "b-/dns-a2cname-deploy"
reclone = true
file_paths = ["compose.yaml", "ts.yaml"]
environment = """
#TS_AUTHKEY=[[OP__KOMODO__DNS_SERVER_STATIC__CREDENTIAL]]?ephemeral=true
TS_AUTHKEY=[[OP__KOMODO__DNS_SERVER_STATIC__CREDENTIAL]]
"""

##

[[procedure]]
name = "deploy_dns-a2cname"
tags = ["dns-a2cname", "instance"]

[[procedure.config.stage]]
name = "Sync 🔄"
enabled = true
executions = [
  { execution.type = "RunSync", execution.params.sync = "dns-a2cname_syncs", enabled = true },
  { execution.type = "RunSync", execution.params.sync = "dns-a2cname_stacks", enabled = true }
]

[[procedure.config.stage]]
name = "Deploy 🚀"
enabled = true
executions = [
  { execution.type = "BatchDeployStackIfChanged", execution.params.pattern = "dns-a2cname_*", enabled = true }
]