[[stack]]
name = "dns-a2cname_1"
tags = ["dns-a2cname", "instance"]
[stack.config]
server = "localhost"
git_account = "b-"
repo = "b-/dns-a2cname-deploy"
reclone = true
file_paths = ["compose.yaml", "ts.yaml"]
environment = """
#TS_AUTHKEY=[[OP__KOMODO__TAILSCALE_OP__CLIENT_SECRET]]?ephemeral=true
TS_AUTHKEY=[[OP__KOMODO__TAILSCALE_OP__CLIENT_SECRET]]
"""
